version: '2'
services:
  v3-n0.12:
    extends:
      file: docker/defaults.yml
      service: defaults
    container_name: v3-n0.12
    build:
      dockerfile: v3-n0.12/Dockerfile
    labels:
      com.esjs.nodev: "0.12"
      com.esjs.esjsv: "3"
    
  v4-n0.12:
    extends:
      file: docker/defaults.yml
      service: defaults
    container_name: v4-n0.12
    build:
      dockerfile: v4-n0.12/Dockerfile
    labels:
      com.esjs.nodev: "0.12"
      com.esjs.esjsv: "4"
    
  v12-n0.12:
    extends:
      file: docker/defaults.yml
      service: defaults
    container_name: v12-n0.12
    build:
      dockerfile: v12-n0.12/Dockerfile
    labels:
      com.esjs.nodev: "0.12"
      com.esjs.esjsv: "12"
    
  v12-n4:
    extends:
      file: docker/defaults.yml
      service: defaults
    container_name: v12-n4
    build:
      dockerfile: v12-n4/Dockerfile
    labels:
      com.esjs.nodev: "4"
      com.esjs.esjsv: "12"
    
  master-n7:
    extends:
      file: docker/defaults.yml
      service: defaults
    container_name: master-n7
    build:
      dockerfile: master-n7/Dockerfile
    labels:
      com.esjs.nodev: "7"
      com.esjs.esjsv: "master"
