version: '2'
services:
  master-n0.12:
    container_name: master-n0.12
    build:
      context: docker
      dockerfile: master-n0.12/Dockerfile
    labels:
      com.esjs.nodev: '0.12'
      com.esjs.esjsv: master
      com.esjs.memlimit: 1G
    env_file: docker/.env
    network_mode: host
    privileged: true
    read_only: true
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
  master-n4:
    container_name: master-n4
    build:
      context: docker
      dockerfile: master-n4/Dockerfile
    labels:
      com.esjs.nodev: '4'
      com.esjs.esjsv: master
      com.esjs.memlimit: 1G
    env_file: docker/.env
    network_mode: host
    privileged: true
    read_only: true
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
  master-n7:
    container_name: master-n7
    build:
      context: docker
      dockerfile: master-n7/Dockerfile
    labels:
      com.esjs.nodev: '7'
      com.esjs.esjsv: master
      com.esjs.memlimit: 1G
    env_file: docker/.env
    network_mode: host
    privileged: true
    read_only: true
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
  master_old_lodash-n0.12:
    container_name: master_old_lodash-n0.12
    build:
      context: docker
      dockerfile: master_old_lodash-n0.12/Dockerfile
    labels:
      com.esjs.nodev: '0.12'
      com.esjs.esjsv: master_old_lodash
      com.esjs.memlimit: 1G
    env_file: docker/.env
    network_mode: host
    privileged: true
    read_only: true
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
  master_old_lodash-n4:
    container_name: master_old_lodash-n4
    build:
      context: docker
      dockerfile: master_old_lodash-n4/Dockerfile
    labels:
      com.esjs.nodev: '4'
      com.esjs.esjsv: master_old_lodash
      com.esjs.memlimit: 1G
    env_file: docker/.env
    network_mode: host
    privileged: true
    read_only: true
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
  master_old_lodash-n7:
    container_name: master_old_lodash-n7
    build:
      context: docker
      dockerfile: master_old_lodash-n7/Dockerfile
    labels:
      com.esjs.nodev: '7'
      com.esjs.esjsv: master_old_lodash
      com.esjs.memlimit: 1G
    env_file: docker/.env
    network_mode: host
    privileged: true
    read_only: true
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
  master_stable_prototype-n0.12:
    container_name: master_stable_prototype-n0.12
    build:
      context: docker
      dockerfile: master_stable_prototype-n0.12/Dockerfile
    labels:
      com.esjs.nodev: '0.12'
      com.esjs.esjsv: master_stable_prototype
      com.esjs.memlimit: 1G
    env_file: docker/.env
    network_mode: host
    privileged: true
    read_only: true
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
  master_stable_prototype-n4:
    container_name: master_stable_prototype-n4
    build:
      context: docker
      dockerfile: master_stable_prototype-n4/Dockerfile
    labels:
      com.esjs.nodev: '4'
      com.esjs.esjsv: master_stable_prototype
      com.esjs.memlimit: 1G
    env_file: docker/.env
    network_mode: host
    privileged: true
    read_only: true
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
  master_stable_prototype-n7:
    container_name: master_stable_prototype-n7
    build:
      context: docker
      dockerfile: master_stable_prototype-n7/Dockerfile
    labels:
      com.esjs.nodev: '7'
      com.esjs.esjsv: master_stable_prototype
      com.esjs.memlimit: 1G
    env_file: docker/.env
    network_mode: host
    privileged: true
    read_only: true
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
  v12-n0.12:
    container_name: v12-n0.12
    build:
      context: docker
      dockerfile: v12-n0.12/Dockerfile
    labels:
      com.esjs.nodev: '0.12'
      com.esjs.esjsv: '12'
      com.esjs.memlimit: 1G
    env_file: docker/.env
    network_mode: host
    privileged: true
    read_only: true
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
  v12-n4:
    container_name: v12-n4
    build:
      context: docker
      dockerfile: v12-n4/Dockerfile
    labels:
      com.esjs.nodev: '4'
      com.esjs.esjsv: '12'
      com.esjs.memlimit: 1G
    env_file: docker/.env
    network_mode: host
    privileged: true
    read_only: true
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
  v12-n7:
    container_name: v12-n7
    build:
      context: docker
      dockerfile: v12-n7/Dockerfile
    labels:
      com.esjs.nodev: '7'
      com.esjs.esjsv: '12'
      com.esjs.memlimit: 1G
    env_file: docker/.env
    network_mode: host
    privileged: true
    read_only: true
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
  v3-n0.12:
    container_name: v3-n0.12
    build:
      context: docker
      dockerfile: v3-n0.12/Dockerfile
    labels:
      com.esjs.nodev: '0.12'
      com.esjs.esjsv: '3'
      com.esjs.memlimit: 1G
    env_file: docker/.env
    network_mode: host
    privileged: true
    read_only: true
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
  v4-n0.12:
    container_name: v4-n0.12
    build:
      context: docker
      dockerfile: v4-n0.12/Dockerfile
    labels:
      com.esjs.nodev: '0.12'
      com.esjs.esjsv: '4'
      com.esjs.memlimit: 1G
    env_file: docker/.env
    network_mode: host
    privileged: true
    read_only: true
    restart: always
    mem_limit: 1G
    memswap_limit: 1G
